### ISSUE TITLE
Better yaml parsing and error reporting

### ISSUE THREAD

**Issue by lczech** [snakemake/snakemake-executor-plugin-slurm#176]
**Is your feature request related to a problem? Please describe.**
I just tried to use a profile that contained valid yaml, yet not to the exact specs of this plugin:

```
default-resources:
  - slurm_account: your_account
  - slurm_partition: your_partition
```

That is, using `-` lists instead of key-value pair entries.

This just led to a red wall of tracebacks:

```
Traceback (most recent call last):

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/cli.py", line 2179, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/cli.py", line 1785, in parse_args
    args = parser.parse_args(argv)
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/configargparse.py", line 797, in parse_args
    args, argv = self.parse_known_args(
                 ^^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/configargparse.py", line 979, in parse_known_args
    namespace, unknown_args = argparse.ArgumentParser.parse_known_args(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/argparse.py", line 1924, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/argparse.py", line 2136, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/argparse.py", line 2076, in consume_optional
    take_action(action, args, option_string)

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/argparse.py", line 2000, in take_action
    action(self, namespace, argument_values, option_string)

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/common/argparse.py", line 54, in __call__
    parsed = parse_func(values)
             ^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake_interface_executor_plugins/utils.py", line 168, in inner
    return apply_parser(decoded)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake_interface_executor_plugins/utils.py", line 160, in apply_parser
    return parser_func(args)
           ^^^^^^^^^^^^^^^^^

  File "/global/home/users/lucasczech/micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/resources.py", line 60, in __init__
    {name: value for name, value in map(self.decode_arg, args)}
                     ^^^^^^^^^^^

ValueError: not enough values to unpack (expected 2, got 1)
```

and looking at that traceback, it looked to me that I somehow mis-specified the snakemake command line call. Took me a while to figure out where the issue was coming from.

**Describe the solution you'd like**
I'd suggest to catch errors in the yaml parsing routine of the executor, and add a more helpful warning to the user.

**Comment by cmeesters** [comment]
This is, as the error indicates, part of the Snakemake core, I'm afraid. It, in turn, falls back to the PyYAML package. So yes, the current way is to write:

```yaml
default-resources:
    slurm_account: "account"
    slurm_partition: "partition"

set-threads:
    <rule_name>: <number>
    
set-resources:
   <rule_name>:
       <parameter>: <number or string>
```

Mind the quotation marks for strings to be safe.
