### ISSUE TITLE
Traceback when trying to execute workflow with 0.2.1 release

### ISSUE THREAD

**Issue by ocaisa** [snakemake/snakemake-executor-plugin-slurm#21]
I'm porting a v7 workflow to v8 and am struggling to get a simple Snakefile to execute, I get a traceback:
```
[ocaisa@node1 files]$ pip freeze | grep ^snakemake
snakemake @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemake/snakemake-8.1.2
snakemake-executor-plugin-cluster-generic @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeexecutorpluginclustergeneric/snakemake_executor_plugin_cluster_generic-1.0.7
snakemake-executor-plugin-cluster-sync @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeexecutorpluginclustersync/snakemake_executor_plugin_cluster_sync-0.1.3
snakemake-executor-plugin-flux @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeexecutorpluginflux/snakemake_executor_plugin_flux-0.1.0
snakemake-executor-plugin-slurm @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeexecutorpluginslurm/snakemake_executor_plugin_slurm-0.2.1
snakemake-executor-plugin-slurm-jobstep @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeexecutorpluginslurmjobstep/snakemake_executor_plugin_slurm_jobstep-0.1.10
snakemake-interface-common @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeinterfacecommon/snakemake_interface_common-1.15.1
snakemake-interface-executor-plugins @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeinterfaceexecutorplugins/snakemake_interface_executor_plugins-8.2.0
snakemake-interface-storage-plugins @ file:///tmp/ocaisa/easybuild/build/snakemake/8.1.2/foss-2023a/snakemakeinterfacestorageplugins/snakemake_interface_storage_plugins-3.0.0
[ocaisa@node1 files]$ snakemake --snakefile Snakefile_cluster_iteration -j 2 --executor slurm --jobscript ./cluster/slurm_jobscript.sh
Building DAG of jobs...
Retrieving input from storage.
Using shell: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/bash
Provided remote nodes: 2
Job stats:
job        count
-------  -------
iterate        2
plot           1
total          3

Select jobs to execute...
Execute 2 jobs...

[Thu Jan 18 19:43:53 2024]
rule iterate:
    output: 2.out
    jobid: 2
    reason: Missing output files: 2.out; Code has changed since last execution
    wildcards: sample=2
    resources: tmpdir=<TBD>, mpi=mpirun, tasks=2

No SLURM account given, trying to guess.
Guessed SLURM account: def-users
No wall time information given. This might or might not work on your cluster. If not, specify the resource runtime in your rule or as a reasonable default via --default-resources.
No job memory information ('mem_mb' or 'mem_mb_per_cpu') is given - submitting without. This might or might not work on your cluster.
Traceback (most recent call last):
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/cli.py", line 1962, in args_to_api
    dag_api.execute_workflow(
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/api.py", line 564, in execute_workflow
    workflow.execute(
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/workflow.py", line 1218, in execute
    raise e
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/workflow.py", line 1214, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/scheduler.py", line 289, in schedule
    self.run(runjobs)
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake/scheduler.py", line 368, in run
    executor.run_jobs(jobs)
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 72, in run_jobs
    self.run_job(job)
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake_executor_plugin_slurm/__init__.py", line 126, in run_job
    exec_job = self.format_job_exec(job)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/software/snakemake/8.1.2-foss-2023a/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 151, in format_job_exec
    general_args = self.workflow.spawned_job_args_factory.general_args(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpawnedJobArgsFactory.general_args() got an unexpected keyword argument 'pass_group_args'
```
I'm a snakemake novice but I notice `pass_group_args` is related to recent commits in the various repos, so there may be something related to that.

**Comment by ocaisa** [comment]
I comment out the offending line, the workflow seems to execute ok.

**Comment by ocaisa** [comment]
This was my fault, I'd used version 8.1.2 instead of 8.2.1 of snakemake
