### ISSUE TITLE
Job status query fails if slurm accounting storage is disabled

### ISSUE THREAD

**Issue by prs513rosewood** [snakemake/snakemake-executor-plugin-slurm#38]
I get an error when running a job on with a slurm instance whose accounting storage is disabled (i.e. the `sacct` command just replies `Slurm accounting storage is disabled`). Here's the stack trace :

```
The job status query failed with command: sacct -X --parsable2 --noheader --format=JobIdRaw,State --starttime 2024-02-21T16:00 --endtime now --name ddcf5013-8004-418b-8832-9a563aaf5280
Error message: Slurm accounting storage is disabled

argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/rosewood/venvs/aging_stearic/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/remote.py", line 190, in _wait_thread
    asyncio.run(self._wait_for_jobs())
  File "/home/rosewood/stage/spack-0.21.1/opt/spack/linux-centos7-k10/gcc-8.3.1/python-3.11.6-aunbzdzafawzwjwh4wtq45ftn2zjmnzw/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/rosewood/stage/spack-0.21.1/opt/spack/linux-centos7-k10/gcc-8.3.1/python-3.11.6-aunbzdzafawzwjwh4wtq45ftn2zjmnzw/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rosewood/stage/spack-0.21.1/opt/spack/linux-centos7-k10/gcc-8.3.1/python-3.11.6-aunbzdzafawzwjwh4wtq45ftn2zjmnzw/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rosewood/venvs/aging_stearic/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/remote.py", line 180, in _wait_for_jobs
    still_active_jobs = [
                        ^
  File "/home/rosewood/venvs/aging_stearic/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/remote.py", line 180, in <listcomp>
    still_active_jobs = [
                        ^
  File "/home/rosewood/venvs/aging_stearic/lib/python3.11/site-packages/snakemake_executor_plugin_slurm/__init__.py", line 263, in check_active_jobs
    if j.external_jobid not in status_of_jobs:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Looks like there's some error handling here: https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/7e3de33ab447cd3415e53464019cce8e7361bda8/snakemake_executor_plugin_slurm/__init__.py#L221

But after the loop over attempts to get job status the rest of the code assumes no error and treats `status_of_jobs` as a valid set.

The slurm profile also uses `sacct` but falls back to `scontrol` if that fails, might be a solution : https://github.com/Snakemake-Profiles/slurm/blob/c44315217d1ce36493dc7dccbd013528657747f9/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-status.py#L40

**Comment by prs513rosewood** [comment]
Thanks for looking at this, I know this is a weird edge case. The cluster in question is somewhat artisanal.

I think the slurm cluster profile may be a workable fallback for me, so the only important issue how to gracefully handle the error if `status_of_jobs` is invalid (which may happen for other reasons). I think I can submit a fix.

**Comment by hmkim** [comment]
As you mentioned, sometimes slurm accouting is not enabled in non-production and the way to support this is to use the 

[cluster-generic](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/cluster-generic.html)  plugin to run the job, is that correct?



```

 snakemake \
         --executor cluster-generic \
         --cluster-generic-submit-cmd 'sbatch --job-name={rule} --partition={my_partion_name} --cpus-per-task={threads} --export=ALL --chdir=$PWD' \
         --jobs unlimited
```

**Comment by alisonpeard** [comment]
Seconding this issue with my departmental cluster, I'm getting this warning repeatedly:

```
Select jobs to execute...
The job status query failed with command 'sacct -X --parsable2 --clusters all --noheader --format=JobIdRaw,State --starttime 2025-04-21T10:00 --endtime now --name 1e6f8520-2f9b-4cad-8990-6b2e6fa24e9d'Error message: 'Slurm accounting storage is disabled'This error message is not expected, please report it back to us.
The job status query failed with command 'sacct -X --parsable2 --clusters all --noheader --format=JobIdRaw,State --starttime 2025-04-21T10:00 --endtime now --name 1e6f8520-2f9b-4cad-8990-6b2e6fa24e9d'Error message: 'Slurm accounting storage is disabled'This error message is not expected, please report it back to us.
```

My departmental cluster won't have SLURM accounting storage up and running for a few months, are there any workarounds?

**Comment by cmeesters** [comment]
I'm afraid, the plugin cannot fix your cluster ;-). So, the background is this: Using `squeue` you can check the status of pending and running jobs. `sacct` will add information about past jobs. So, without accounting, your favourite workflow manager cannot know whether a job has been successful, I'm afraid.
